lang: en
timezone: America/New_York

title: Coderack
tagline: "Technology + healthcare."
description: >-
  Matt is a techie that is passionate about bringing new technology to
  healthcare. You can find his personal thoughts and ideas here.
url: "https://coderack.com"
baseurl: ""
email: hello@coderack.com

theme: jekyll-theme-chirpy
img_cdn: ""
avatar: /assets/img/headshot.jpeg

github:
  username: mattracki
twitter:
  username: racki_matt

social:
  name: Matt Racki
  email: hello@coderack.com
  links:
    - https://github.com/mattracki
    - https://twitter.com/racki_matt
    - mailto:hello@coderack.com
    - https://www.linkedin.com/in/racki/

author:
  name: Matt Racki
  bio: CTO at Epion Health focused on patient-first technology.
  links:
    - label: Email
      icon: fas fa-envelope
      url: mailto:hello@coderack.com
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/mattracki
    - label: Twitter
      icon: fab fa-twitter
      url: https://twitter.com/racki_matt
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://www.linkedin.com/in/racki/

collections:
  tabs:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: tabs
    values:
      layout: page

permalink: /posts/:title/
paginate: 3
paginate_path: /page:num/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

comments:
  provider: ""

analytics:
  provider: ""
